version: '3'
services:
  python:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./python:/workspace
  node:
    build: node
    ports:
      - 8080:8080
    volumes:
      - ./node:/workspace
      - /workspace/node_modules